#
# Regenerate cmake/Sources.cmake from the original VC6 .dsp project files.
#
# Run from anywhere:  cmake -P cmake/gen_sources.cmake
#
# The .dsp files remain the source of truth for which translation units belong
# to which target, so this reads them rather than globbing -- globbing would
# silently pick up stray files and would not survive someone adding a file to
# the .dsp.
#
# This is a script-mode (-P) tool, not part of the configure step: Sources.cmake
# is committed, so an ordinary build never runs it. Re-run it after adding or
# removing a file from a .dsp and commit the result.
#
# It is written in CMake rather than a scripting language on purpose. CMake is
# already required to build this tree, so the generator costs no dependency
# beyond what a build needs anyway.
#

cmake_minimum_required(VERSION 3.20)

get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}" DIRECTORY)
set(CODE "${ROOT}/Code")
set(OUT "${ROOT}/cmake/Sources.cmake")

# CMake variable name -> .dsp file, relative to Code/
set(TARGETS
    "WWDEBUG"       "wwdebug/wwdebug.dsp"
    "WWBITPACK"     "wwbitpack/wwbitpack.dsp"
    "WWMATH"        "WWMath/wwmath.dsp"
    "WWLIB"         "wwlib/wwlib.dsp"
    "WWSAVELOAD"    "wwsaveload/wwsaveload.dsp"
    "WWNET"         "wwnet/wwnet.dsp"
    "WWTRANSLATEDB" "wwtranslatedb/wwtranslatedb.dsp"
    "WWUTIL"        "wwutil/wwutil.dsp"
    "WW3D2"         "ww3d2/ww3d2.dsp"
    "WWPHYS"        "wwphys/wwphys.dsp"
    "WWUI"          "wwui/wwui.dsp"
    "WWAUDIO"       "WWAudio/WWAudio.dsp"
    "COMBAT"        "Combat/Combat.dsp"
    "BINKMOVIE"     "BinkMovie/BinkMovie.dsp"
    "SCONTROL"      "SControl/SControl.dsp"
    "BANDTEST"      "BandTest/BandTest.dsp"
    "SCRIPTS"       "Scripts/Scripts.dsp"
    "COMMANDO"      "Commando/commando.dsp")

# parse_sources(<dsp path> <out var>)
#
# Sets <out var> to the translation units listed in a .dsp, as paths relative to
# the repo root. SOURCE= entries are relative to the directory holding the .dsp
# and use backslashes. Headers and the assorted .txt files the original authors
# parked in the projects are skipped.
function(parse_sources DSP_PATH OUT_VAR)
    get_filename_component(proj_dir "${DSP_PATH}" DIRECTORY)

    # file(STRINGS) keeps only printable-ASCII runs, which is exactly right
    # here: the .dsp files are not all valid UTF-8, and every SOURCE= line is
    # plain ASCII. Whatever the binary stretches become does not matter.
    file(STRINGS "${DSP_PATH}" lines)

    set(found "")
    foreach(line IN LISTS lines)
        string(REGEX REPLACE "\r$" "" line "${line}")
        string(STRIP "${line}" line)
        if(NOT line MATCHES "^SOURCE=")
            continue()
        endif()

        string(REGEX REPLACE "^SOURCE=" "" raw "${line}")
        string(STRIP "${raw}" raw)
        string(REGEX REPLACE [[^"(.*)"$]] [[\1]] raw "${raw}")

        string(TOLOWER "${raw}" lowered)
        if(NOT lowered MATCHES [[\.(cpp|c)$]])
            continue()
        endif()
        if(raw MATCHES [[\$\(InputPath\)]])
            continue()
        endif()

        string(REPLACE "\\" "/" raw "${raw}")
        # ABSOLUTE collapses the leading .\ and any ..\ segments.
        get_filename_component(abs_path "${proj_dir}/${raw}" ABSOLUTE)
        file(RELATIVE_PATH rel "${ROOT}" "${abs_path}")

        if(NOT EXISTS "${abs_path}")
            message(STATUS "    ! listed but missing, skipped: ${rel}")
            continue()
        endif()
        if(NOT rel IN_LIST found)
            list(APPEND found "${rel}")
        endif()
    endforeach()

    set(${OUT_VAR} "${found}" PARENT_SCOPE)
endfunction()

set(text "# Generated by cmake/gen_sources.cmake -- do not edit by hand.\n")
string(APPEND text "# Source lists are extracted from the original VC6 .dsp project files.\n\n")

list(LENGTH TARGETS target_count)
math(EXPR last "${target_count} - 1")
foreach(i RANGE 0 ${last} 2)
    list(GET TARGETS ${i} var)
    math(EXPR j "${i} + 1")
    list(GET TARGETS ${j} dsp)

    set(dsp_path "${CODE}/${dsp}")
    if(NOT EXISTS "${dsp_path}")
        message(FATAL_ERROR "missing project file: ${dsp_path}")
    endif()

    message(STATUS "${var} <- ${dsp}")
    parse_sources("${dsp_path}" sources)
    list(LENGTH sources count)
    message(STATUS "    ${count} sources")

    string(APPEND text "set(${var}_SOURCES\n")
    foreach(src IN LISTS sources)
        string(APPEND text "    ${src}\n")
    endforeach()
    string(APPEND text ")\n\n")
endforeach()

# The loop leaves a blank line after the last ")"; the file ends at the paren.
string(REGEX REPLACE "\n$" "" text "${text}")

# file(WRITE) opens in text mode on Windows and would turn every newline into
# CRLF. file(CONFIGURE) can be told otherwise. @ONLY because the content is
# finished text -- there is no @VAR@ in it and nothing should be substituted.
file(CONFIGURE OUTPUT "${OUT}" CONTENT "${text}" @ONLY NEWLINE_STYLE LF)

file(RELATIVE_PATH out_rel "${ROOT}" "${OUT}")
message(STATUS "")
message(STATUS "wrote ${out_rel}")
